const std = @import("std");
const vaxis = @import("vaxis");

/// Set the default panic handler to the vaxis panic_handler. This will clean up the terminal if any
/// panics occur
pub const panic = vaxis.panic_handler;

/// Set some scope levels for the vaxis scopes
pub const std_options: std.Options = .{
    .log_scope_levels = &.{
        .{ .scope = .vaxis, .level = .warn },
        .{ .scope = .vaxis_parser, .level = .warn },
    },
};

/// Tagged union of all events our application will handle. These can be generated by Vaxis or your
/// own custom events
const Event = union(enum) {
    key_press: vaxis.Key,
    key_release: vaxis.Key,
    mouse: vaxis.Mouse,
    focus_in, // window has gained focus
    focus_out, // window has lost focus
    paste_start, // bracketed paste start
    paste_end, // bracketed paste end
    paste: []const u8, // osc 52 paste, caller must free
    color_report: vaxis.Color.Report, // osc 4, 10, 11, 12 response
    color_scheme: vaxis.Color.Scheme, // light / dark OS theme changes
    winsize: vaxis.Winsize, // the window size has changed. This event is always sent when the loop
    // is started
};

const State = enum { Child, Tiles, Battle };

/// The application state
const MyApp = struct {
    allocator: std.mem.Allocator,
    // A flag for if we should quit
    should_quit: bool,
    /// The tty we are talking to
    tty: vaxis.Tty,
    /// The vaxis instance
    vx: vaxis.Vaxis,
    /// A mouse event that we will handle in the draw cycle
    mouse: ?vaxis.Mouse,

    /// A struct with all app variables
    app: struct {
        menu: struct {
            active: bool = false,
            state: State = .Child,
        } = .{},

        state: union(State) {
            Child: struct {
                state: enum { hello, goodbye } = .hello,

                color: struct {
                    r: bool = true,
                    g: bool = true,
                    b: bool = true,
                } = .{},
                hovered: bool = false,
                clicked: bool = false,
            },

            Tiles: struct {
                state: enum { selection, tiles } = .selection,

                uni: ?vaxis.Unicode = null,
                input: ?vaxis.widgets.TextInput = null,

                height: ?usize = null,
                width: ?usize = null,

                colors: ?[][]vaxis.Color = null,
            },

            Battle: struct {
                pub const Attack = struct {
                    name: []const u8,
                    damage: u32,
                };

                menuState: enum { main, attack } = .main,

                attacks: [4]?Attack = .{ null, null, null, null },
            },
        } = .{ .Child = .{} },
    } = .{},

    pub fn init(allocator: std.mem.Allocator) !MyApp {
        return .{
            .allocator = allocator,
            .should_quit = false,
            .tty = try vaxis.Tty.init(),
            .vx = try vaxis.init(allocator, .{}),
            .mouse = null,
        };
    }

    pub fn deinit(self: *MyApp) void {
        // Deinit takes an optional allocator. You can choose to pass an allocator to clean up
        // memory, or pass null if your application is shutting down and let the OS clean up the
        // memory
        self.vx.deinit(self.allocator, self.tty.anyWriter());
        self.tty.deinit();

        self.detiles();
    }

    pub fn detiles(self: *MyApp) void {
        switch (self.app.state) {
            .Tiles => |*Tiles| {
                if (Tiles.input) |*input| input.*.deinit();
                if (Tiles.uni) |uni| uni.deinit();

                if (Tiles.colors) |colors| {
                    for (colors) |row| {
                        self.allocator.free(row);
                    }
                    self.allocator.free(colors);
                }
            },
            else => unreachable,
        }
    }

    pub fn run(self: *MyApp) !void {
        // Initialize our event loop. This particular loop requires intrusive init
        var loop: vaxis.Loop(Event) = .{
            .tty = &self.tty,
            .vaxis = &self.vx,
        };
        try loop.init();

        // Start the event loop. Events will now be queued
        try loop.start();

        try self.vx.enterAltScreen(self.tty.anyWriter());

        // Query the terminal to detect advanced features, such as kitty keyboard protocol, etc.
        // This will automatically enable the features in the screen you are in, so you will want to
        // call it after entering the alt screen if you are a full screen application. The second
        // arg is a timeout for the terminal to send responses. Typically the response will be very
        // fast, however it could be slow on ssh connections.
        try self.vx.queryTerminal(self.tty.anyWriter(), 1 * std.time.ns_per_s);

        // Enable mouse events
        try self.vx.setMouseMode(self.tty.anyWriter(), true);

        // This is the main event loop. The basic structure is
        // 1. Handle events
        // 2. Draw application
        // 3. Render
        while (!self.should_quit) {
            // pollEvent blocks until we have an event
            loop.pollEvent();
            // tryEvent returns events until the queue is empty
            while (loop.tryEvent()) |event| {
                try self.update(event);
            }
            // Draw our application after handling events
            self.draw();

            // It's best to use a buffered writer for the render method. TTY provides one, but you
            // may use your own. The provided bufferedWriter has a buffer size of 4096
            var buffered = self.tty.bufferedWriter();
            // Render the application to the screen
            try self.vx.render(buffered.writer().any());
            try buffered.flush();
        }
    }

    /// Update our application state from an event
    pub fn update(self: *MyApp, event: Event) !void {
        // universal events
        switch (event) {
            .key_press => |key| {
                if (key.matches('c', .{ .ctrl = true })) {
                    self.should_quit = true;
                    return;
                }

                if (key.matches(vaxis.Key.escape, .{}) and (!self.app.menu.active)) {
                    self.app.menu.active = true;
                }
            },
            .mouse => |mouse| self.mouse = mouse,
            .winsize => |ws| try self.vx.resize(self.allocator, self.tty.anyWriter(), ws),
            else => {},
        }
        // no event handling while in the menu
        if (self.app.menu.active) {
            switch (event) {
                .key_press => |key| {
                    const len = @typeInfo(State).Enum.fields.len;
                    const cp0 = 48; // codepoint of 0
                    //
                    if (key.matchExact(vaxis.Key.tab, .{})) {
                        const int = @intFromEnum(self.app.menu.state);
                        self.app.menu.state = @enumFromInt((int + 1) % len);
                    }
                    if ((key.codepoint > cp0) and (key.codepoint <= cp0 + len)) {
                        self.app.menu.state = @enumFromInt(key.codepoint - cp0 - 1);
                    }
                    if (key.matches(vaxis.Key.enter, .{})) {
                        if ((self.app.state == .Tiles) and (self.app.menu.state != .Tiles))
                            self.detiles();
                        switch (self.app.menu.state) {
                            .Child => {
                                self.app.state = .{ .Child = .{} };
                            },
                            .Tiles => {
                                self.app.state = .{ .Tiles = .{} };
                                switch (self.app.state) {
                                    .Tiles => |*Tiles| {
                                        Tiles.uni = try vaxis.Unicode.init(self.allocator);
                                        Tiles.input = vaxis.widgets.TextInput.init(
                                            self.allocator,
                                            &Tiles.uni.?,
                                        );
                                    },
                                    else => unreachable,
                                }
                            },
                            .Battle => {
                                self.app.state = .{ .Battle = .{} };
                            },
                        }
                        self.app.menu.active = false;
                    }
                },
                else => {},
            }
            return;
        }
        // state specific events
        switch (self.app.state) {
            //Bchild state
            .Child => |*Child| switch (event) {
                .key_press => |key| {
                    // key.matches does some basic matching algorithms. Key matching can be complex in
                    // the presence of kitty keyboard encodings, this will generally be a good approach.
                    // There are other matching functions available for specific purposes, as well
                    if (!Child.clicked) {
                        if (key.matches('r', .{}))
                            Child.color.r = !Child.color.r;
                        if (key.matches('g', .{}))
                            Child.color.g = !Child.color.g;
                        if (key.matches('b', .{}))
                            Child.color.b = !Child.color.b;
                    }
                    if (key.matches('q', .{}) and (Child.state == .goodbye))
                        self.should_quit = true;
                },
                else => {},
            },
            .Tiles => |*Tiles| {
                switch (Tiles.state) {
                    .selection => {
                        switch (event) {
                            .key_press => |key| {
                                if (key.matches(vaxis.Key.enter, .{})) {
                                    _ = 0;
                                } else try Tiles.input.?.update(.{ .key_press = key });
                            },
                            else => {},
                        }

                        //var seed: u64 = 0;
                        //try std.posix.getrandom(std.mem.asBytes(&seed));
                        //var prng = std.rand.DefaultPrng.init(seed);
                        //const rand = prng.random();

                        //Tiles.height = (rand.int(u4) % 10) + 1;
                        //Tiles.width = (rand.int(u4) % 10) + 1;

                        //Tiles.colors =
                        //    try self.allocator.alloc([]vaxis.Color, Tiles.height.?);

                        //for (Tiles.colors.?) |*row| {
                        //    row.* = try self.allocator.alloc(vaxis.Color, Tiles.width.?);
                        //    for (row.*) |*color| {
                        //        const r = rand.int(u8);
                        //        const g = rand.int(u8);
                        //        const b = rand.int(u8);
                        //        color.* = .{ .rgb = [_]u8{ r, g, b } };
                        //    }
                        //}

                        //Tiles.state = .tiles;
                    },
                    .tiles => {},
                }
            },
            .Battle => |Battle| {
                _ = Battle;
            },
        }
    }

    /// Draw our current state
    pub fn draw(self: *MyApp) void {
        var redraw: bool = false;

        // Window is a bounded area with a view to the screen. You cannot draw outside of a windows
        // bounds. They are light structures, not intended to be stored.
        const win = self.vx.window();

        // Clearing the window has the effect of setting each cell to it's "default" state. Vaxis
        // applications typically will be immediate mode, and you will redraw your entire
        // application during the draw cycle.
        win.clear();
        win.hideCursor();

        // In addition to clearing our window, we want to clear the mouse shape state since we may
        // be changing that as well
        self.vx.setMouseShape(.default);

        if (self.app.menu.active) {
            const states = @typeInfo(State).Enum.fields;

            const menu = win.child(.{
                .x_off = 1,
                .y_off = 1,
                .width = .{ .limit = win.width - 2 },
                .height = .{ .limit = (states.len * 2) + 1 },
            });

            const msg = "Select the app to run";
            _ = try menu.printSegment(.{ .text = msg }, .{});

            inline for (0..states.len) |i| {
                const style = vaxis.Style{
                    .reverse = (i == @intFromEnum(self.app.menu.state)),
                };
                const num = [1]u8{'1' + i};
                const text = "[" ++ num ++ "]";
                _ = try menu.printSegment(.{
                    .text = text,
                    .style = .{},
                }, .{ .row_offset = 2 * (i + 1) });
                _ = try menu.printSegment(.{
                    .text = states[i].name,
                    .style = style,
                }, .{ .row_offset = 2 * (i + 1), .col_offset = 4 });
            }
        } else switch (self.app.state) {
            .Child => |*Child| {

                // set the message
                const msg = switch (Child.state) {
                    .hello => "Hello, world!",
                    .goodbye => "Goodbye, world!",
                };

                const child_win = win.child(.{
                    .x_off = (win.width / 2) - (msg.len / 2),
                    .y_off = win.height / 2 + 1,
                    .width = .{ .limit = msg.len },
                    .height = .{ .limit = 1 },
                });

                // mouse events are much easier to handle in the draw cycle. Windows have a helper method to
                // determine if the event occurred in the target window. This method returns null if there
                // is no mouse event, or if it occurred outside of the window

                // start handling mouse events
                const unclicked = if (self.mouse) |mouse| blk: {
                    break :blk (mouse.type == .release);
                } else false;
                var unhovered = (self.mouse != null);

                // window mouse events
                if (child_win.hasMouse(self.mouse)) |mouse| {
                    // mouse shape doesnt work
                    self.vx.setMouseShape(.text);
                    Child.hovered = true;
                    unhovered = false;
                    // button logic
                    if ((mouse.button == .left)) {
                        if (Child.clicked and (mouse.type == .release)) {
                            switch (Child.state) {
                                .hello => Child.state = .goodbye,
                                .goodbye => Child.state = .hello,
                            }
                            redraw = true;
                        }
                        if (mouse.type == .press) Child.clicked = true;
                    }
                    // mouse event handled
                    self.mouse = null;
                }

                // finish handling mouse events
                if (unclicked) Child.clicked = false;
                if (unhovered) Child.hovered = false;

                // define the style of the text in child
                var style = vaxis.Style{
                    .fg = .{ .rgb = [_]u8{ 0, 0, 0 } },
                    .reverse = Child.hovered,
                };

                // change color of text
                if (Child.color.r) {
                    switch (style.fg) {
                        .rgb => |rgb| style.fg = .{ .rgb = [_]u8{ 255, rgb[1], rgb[2] } },
                        else => {},
                    }
                }
                if (Child.color.g) {
                    switch (style.fg) {
                        .rgb => |rgb| style.fg = .{ .rgb = [_]u8{ rgb[0], 255, rgb[2] } },
                        else => {},
                    }
                }
                if (Child.color.b) {
                    switch (style.fg) {
                        .rgb => |rgb| style.fg = .{ .rgb = [_]u8{ rgb[0], rgb[1], 255 } },
                        else => {},
                    }
                }

                // Print a text segment to the screen. This is a helper function which iterates over the
                // text field for graphemes. Alternatively, you can implement your own print functions and
                // use the writeCell API.
                _ = try child_win.printSegment(.{ .text = msg, .style = style }, .{});
            },

            .Tiles => |*Tiles| {
                switch (Tiles.state) {
                    .selection => {
                        const select = win.child(.{
                            .x_off = 1,
                            .y_off = 1,
                            .width = .{ .limit = win.width - 2 },
                            .height = .{ .limit = 2 },
                        });

                        const hMsg = "Input a height (1-10): ";
                        const wMsg = "Input a width (1-10): ";
                        _ = wMsg;
                        _ = try select.printSegment(.{ .text = hMsg }, .{});
                        select.setCursorShape(.underline_blink);
                        select.showCursor(hMsg.len, 0);
                        const hWin = select.child(.{
                            .x_off = hMsg.len,
                            .y_off = 0,
                            .width = .{ .limit = select.width - hMsg.len },
                            .height = .{ .limit = 1 },
                        });
                        Tiles.input.?.draw(hWin);
                    },
                    .tiles => {
                        const height = Tiles.height.?;
                        const width = Tiles.width.?;
                        for (0..height) |h| {
                            for (0..width) |w| {
                                const cell: vaxis.Cell = .{
                                    .char = .{
                                        .grapheme = if ((w + h) % 2 == 0) "/" else "\\",
                                    },
                                    .style = .{
                                        .bg = Tiles.colors.?[h][w],
                                    },
                                };
                                for (((h * win.height) / height)..(((h + 1) * win.height) / height)) |y| {
                                    for (((w * win.width) / width)..(((w + 1) * win.width) / width)) |x| {
                                        win.writeCell(x, y, cell);
                                    }
                                }
                            }
                        }
                    },
                }
            },

            .Battle => |*Battles| {
                _ = Battles;
            },
        }
        // if we need to redraw, call draw again
        if (redraw) self.draw();
    }
};

/// Keep our main function small. Typically handling arg parsing and initialization only
pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer {
        const deinit_status = gpa.deinit();
        //fail test; can't try in defer as defer is executed after we return
        if (deinit_status == .leak) {
            std.log.err("memory leak", .{});
        }
    }
    const allocator = gpa.allocator();

    // Initialize our application
    var app = try MyApp.init(allocator);
    defer app.deinit();

    // Run the application
    try app.run();
}
